######################################################################
# Automatically generated by qmake (2.00a) Sat Feb 17 17:24:31 2007
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
QT += qt3support
# Input
HEADERS += helpdialog.h
FORMS += helpdialog.ui
SOURCES += main.cpp helpdialog.cpp
