/********************************************************************************
** Form generated from reading UI file 'attdatafile.ui'
**
** Created by: Qt User Interface Compiler version 5.1.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ATTDATAFILE_H
#define UI_ATTDATAFILE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_AttDataFile
{
public:
    QGroupBox *groupBoxButtons;
    QPushButton *pushButtonHelp;
    QPushButton *pushButtonClose;
    QPushButton *pushButtonRun;
    QLabel *textLabelLegends1;
    QLabel *textLabelLegends2;
    QLabel *textLabelLegends3;
    QFrame *BorderBottom;
    QFrame *BorderTop;
    QTextBrowser *textBrowserLogs;
    QTabWidget *tabWidget;
    QWidget *tab_1;
    QLineEdit *lineEditPrecipitationFile;
    QPushButton *pushButtonWindVelocityFile;
    QPushButton *pushButtonVaporPressureFile;
    QLineEdit *lineEditVaporPressureFile;
    QLineEdit *lineEditRelativeHumidityFile;
    QLabel *textLabelTemperature;
    QPushButton *pushButtonPrecipitationFile;
    QPushButton *pushButtonRelativeHumidityFile;
    QLabel *textLabelVaporPressure;
    QLineEdit *lineEditWindVelocityFile;
    QPushButton *pushButtonSolarRadiationFile;
    QLineEdit *lineEditSolarRadiationFile;
    QLabel *textLabelSolarRadiation;
    QPushButton *pushButtonTemperatureFile;
    QLabel *textLabelRelativeHumidity;
    QLabel *textLabelPrecipitation;
    QLineEdit *lineEditTemperatureFile;
    QLabel *textLabelWindVelocity;
    QCheckBox *checkBoxPrecipitation;
    QCheckBox *checkBoxTemperature;
    QCheckBox *checkBoxRelativeHumidity;
    QCheckBox *checkBoxWindVelocity;
    QCheckBox *checkBoxSolarRadiation;
    QCheckBox *checkBoxVaporPressure;
    QWidget *tab_2;
    QLabel *textLabelGeologyClasses;
    QLabel *textLabelSoilClasses;
    QPushButton *pushButtonGeologyClassesFile;
    QLineEdit *lineEditMacroporesFile;
    QLabel *textLabelLandCoverClasses;
    QPushButton *pushButtonLandCoverClassesFile;
    QLineEdit *lineEditSoilClassesFile;
    QPushButton *pushButtonMeltRegionsFile;
    QLabel *textLabelMacropores;
    QLabel *textLabelMeltRegions;
    QLineEdit *lineEditGeologyClassesFile;
    QLineEdit *lineEditMeltRegionsFile;
    QPushButton *pushButtonSoilClassesFile;
    QPushButton *pushButtonMacroporesFile;
    QLineEdit *lineEditLandCoverClassesFile;
    QLineEdit *lineEditSourcesSinksFile;
    QLabel *textLabelSourcesSinks;
    QPushButton *pushButtonSourcesSinksFile;
    QCheckBox *checkBoxSoilClasses;
    QCheckBox *checkBoxGeologyClasses;
    QCheckBox *checkBoxMacropores;
    QCheckBox *checkBoxLandCoverClasses;
    QCheckBox *checkBoxMeltRegions;
    QCheckBox *checkBoxSourcesSinks;
    QWidget *tab_3;
    QLabel *textLabelSoilMoisture;
    QLabel *textLabelBoundaryCondition;
    QLineEdit *lineEditInterceptionFile;
    QLineEdit *lineEditSurfaceStorageFile;
    QPushButton *pushButtonSnowCoverFile;
    QLabel *textLabelGroundwater;
    QPushButton *pushButtonGroundwaterFile;
    QPushButton *pushButtonBoundaryConditionFile;
    QLineEdit *lineEditBoundaryConditionFile;
    QLineEdit *lineEditSnowCoverFile;
    QPushButton *pushButtonSurfaceStorageFile;
    QPushButton *pushButtonInterceptionFile;
    QPushButton *pushButtonSoilMoistureFile;
    QLabel *textLabelSnowCover;
    QLineEdit *lineEditGroundwaterFile;
    QLineEdit *lineEditSoilMoistureFile;
    QLabel *textLabelInterception;
    QLabel *textLabelSurfaceStorage;
    QCheckBox *checkBoxSurfaceStorage;
    QCheckBox *checkBoxInterception;
    QCheckBox *checkBoxSnowCover;
    QCheckBox *checkBoxSoilMoisture;
    QCheckBox *checkBoxGroundwater;
    QCheckBox *checkBoxBoundaryCondition;
    QGroupBox *groupBoxOutput;
    QLabel *textLabel1_7;
    QPushButton *pushButtonTINShapeLayerFile;
    QLineEdit *lineEditTINShapeLayerFile;
    QGroupBox *groupBoxOutput_2;
    QLabel *textLabel1_8;
    QPushButton *pushButtonAttDataFile;
    QLineEdit *lineEditAttDataFile;

    void setupUi(QDialog *AttDataFile)
    {
        if (AttDataFile->objectName().isEmpty())
            AttDataFile->setObjectName(QStringLiteral("AttDataFile"));
        AttDataFile->resize(611, 619);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        AttDataFile->setPalette(palette);
        groupBoxButtons = new QGroupBox(AttDataFile);
        groupBoxButtons->setObjectName(QStringLiteral("groupBoxButtons"));
        groupBoxButtons->setGeometry(QRect(15, 460, 581, 61));
        pushButtonHelp = new QPushButton(groupBoxButtons);
        pushButtonHelp->setObjectName(QStringLiteral("pushButtonHelp"));
        pushButtonHelp->setGeometry(QRect(10, 17, 113, 32));
        pushButtonHelp->setAutoDefault(false);
        pushButtonClose = new QPushButton(groupBoxButtons);
        pushButtonClose->setObjectName(QStringLiteral("pushButtonClose"));
        pushButtonClose->setGeometry(QRect(326, 17, 113, 32));
        pushButtonClose->setAutoDefault(false);
        pushButtonRun = new QPushButton(groupBoxButtons);
        pushButtonRun->setObjectName(QStringLiteral("pushButtonRun"));
        pushButtonRun->setGeometry(QRect(460, 17, 113, 32));
        pushButtonRun->setAutoDefault(false);
        textLabelLegends1 = new QLabel(groupBoxButtons);
        textLabelLegends1->setObjectName(QStringLiteral("textLabelLegends1"));
        textLabelLegends1->setGeometry(QRect(139, -1, 121, 31));
        QFont font;
        font.setPointSize(11);
        textLabelLegends1->setFont(font);
        textLabelLegends2 = new QLabel(groupBoxButtons);
        textLabelLegends2->setObjectName(QStringLiteral("textLabelLegends2"));
        textLabelLegends2->setGeometry(QRect(139, 16, 151, 31));
        textLabelLegends2->setFont(font);
        textLabelLegends3 = new QLabel(groupBoxButtons);
        textLabelLegends3->setObjectName(QStringLiteral("textLabelLegends3"));
        textLabelLegends3->setGeometry(QRect(139, 32, 181, 31));
        textLabelLegends3->setFont(font);
        BorderBottom = new QFrame(AttDataFile);
        BorderBottom->setObjectName(QStringLiteral("BorderBottom"));
        BorderBottom->setGeometry(QRect(0, 603, 611, 20));
        BorderBottom->setBaseSize(QSize(0, 0));
        QPalette palette1;
        QBrush brush5(QColor(0, 51, 153, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        QBrush brush6(QColor(128, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush6);
        QBrush brush7(QColor(192, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush7);
        QBrush brush8(QColor(160, 0, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        QBrush brush9(QColor(64, 0, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush9);
        QBrush brush10(QColor(85, 0, 0, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderBottom->setPalette(palette1);
        BorderBottom->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderBottom->setFrameShadow(QFrame::Plain);
        BorderBottom->setLineWidth(12);
        BorderBottom->setMidLineWidth(0);
        BorderBottom->setFrameShape(QFrame::HLine);
        BorderTop = new QFrame(AttDataFile);
        BorderTop->setObjectName(QStringLiteral("BorderTop"));
        BorderTop->setGeometry(QRect(0, -4, 611, 20));
        BorderTop->setBaseSize(QSize(0, 0));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderTop->setPalette(palette2);
        BorderTop->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderTop->setFrameShadow(QFrame::Plain);
        BorderTop->setLineWidth(12);
        BorderTop->setMidLineWidth(0);
        BorderTop->setFrameShape(QFrame::HLine);
        textBrowserLogs = new QTextBrowser(AttDataFile);
        textBrowserLogs->setObjectName(QStringLiteral("textBrowserLogs"));
        textBrowserLogs->setGeometry(QRect(15, 529, 581, 71));
        textBrowserLogs->setLineWrapMode(QTextEdit::NoWrap);
        tabWidget = new QTabWidget(AttDataFile);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(16, 19, 581, 281));
        tab_1 = new QWidget();
        tab_1->setObjectName(QStringLiteral("tab_1"));
        lineEditPrecipitationFile = new QLineEdit(tab_1);
        lineEditPrecipitationFile->setObjectName(QStringLiteral("lineEditPrecipitationFile"));
        lineEditPrecipitationFile->setGeometry(QRect(163, 11, 301, 29));
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        lineEditPrecipitationFile->setFont(font1);
        lineEditPrecipitationFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonWindVelocityFile = new QPushButton(tab_1);
        pushButtonWindVelocityFile->setObjectName(QStringLiteral("pushButtonWindVelocityFile"));
        pushButtonWindVelocityFile->setGeometry(QRect(469, 131, 98, 32));
        pushButtonWindVelocityFile->setCheckable(false);
        pushButtonWindVelocityFile->setAutoDefault(false);
        pushButtonWindVelocityFile->setFlat(false);
        pushButtonVaporPressureFile = new QPushButton(tab_1);
        pushButtonVaporPressureFile->setObjectName(QStringLiteral("pushButtonVaporPressureFile"));
        pushButtonVaporPressureFile->setGeometry(QRect(469, 211, 98, 32));
        pushButtonVaporPressureFile->setCheckable(false);
        pushButtonVaporPressureFile->setAutoDefault(false);
        pushButtonVaporPressureFile->setFlat(false);
        lineEditVaporPressureFile = new QLineEdit(tab_1);
        lineEditVaporPressureFile->setObjectName(QStringLiteral("lineEditVaporPressureFile"));
        lineEditVaporPressureFile->setGeometry(QRect(163, 212, 301, 29));
        lineEditVaporPressureFile->setFont(font1);
        lineEditVaporPressureFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditRelativeHumidityFile = new QLineEdit(tab_1);
        lineEditRelativeHumidityFile->setObjectName(QStringLiteral("lineEditRelativeHumidityFile"));
        lineEditRelativeHumidityFile->setGeometry(QRect(163, 91, 301, 29));
        lineEditRelativeHumidityFile->setFont(font1);
        lineEditRelativeHumidityFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelTemperature = new QLabel(tab_1);
        textLabelTemperature->setObjectName(QStringLiteral("textLabelTemperature"));
        textLabelTemperature->setGeometry(QRect(10, 50, 111, 31));
        pushButtonPrecipitationFile = new QPushButton(tab_1);
        pushButtonPrecipitationFile->setObjectName(QStringLiteral("pushButtonPrecipitationFile"));
        pushButtonPrecipitationFile->setGeometry(QRect(469, 10, 98, 32));
        pushButtonPrecipitationFile->setCheckable(false);
        pushButtonPrecipitationFile->setAutoDefault(false);
        pushButtonPrecipitationFile->setFlat(false);
        pushButtonRelativeHumidityFile = new QPushButton(tab_1);
        pushButtonRelativeHumidityFile->setObjectName(QStringLiteral("pushButtonRelativeHumidityFile"));
        pushButtonRelativeHumidityFile->setGeometry(QRect(469, 90, 98, 32));
        pushButtonRelativeHumidityFile->setCheckable(false);
        pushButtonRelativeHumidityFile->setAutoDefault(false);
        pushButtonRelativeHumidityFile->setFlat(false);
        textLabelVaporPressure = new QLabel(tab_1);
        textLabelVaporPressure->setObjectName(QStringLiteral("textLabelVaporPressure"));
        textLabelVaporPressure->setGeometry(QRect(10, 211, 121, 31));
        lineEditWindVelocityFile = new QLineEdit(tab_1);
        lineEditWindVelocityFile->setObjectName(QStringLiteral("lineEditWindVelocityFile"));
        lineEditWindVelocityFile->setGeometry(QRect(163, 132, 301, 29));
        lineEditWindVelocityFile->setFont(font1);
        lineEditWindVelocityFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonSolarRadiationFile = new QPushButton(tab_1);
        pushButtonSolarRadiationFile->setObjectName(QStringLiteral("pushButtonSolarRadiationFile"));
        pushButtonSolarRadiationFile->setGeometry(QRect(469, 171, 98, 32));
        pushButtonSolarRadiationFile->setCheckable(false);
        pushButtonSolarRadiationFile->setAutoDefault(false);
        pushButtonSolarRadiationFile->setFlat(false);
        lineEditSolarRadiationFile = new QLineEdit(tab_1);
        lineEditSolarRadiationFile->setObjectName(QStringLiteral("lineEditSolarRadiationFile"));
        lineEditSolarRadiationFile->setGeometry(QRect(163, 172, 301, 29));
        lineEditSolarRadiationFile->setFont(font1);
        lineEditSolarRadiationFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelSolarRadiation = new QLabel(tab_1);
        textLabelSolarRadiation->setObjectName(QStringLiteral("textLabelSolarRadiation"));
        textLabelSolarRadiation->setGeometry(QRect(10, 171, 121, 31));
        pushButtonTemperatureFile = new QPushButton(tab_1);
        pushButtonTemperatureFile->setObjectName(QStringLiteral("pushButtonTemperatureFile"));
        pushButtonTemperatureFile->setGeometry(QRect(469, 50, 98, 32));
        pushButtonTemperatureFile->setCheckable(false);
        pushButtonTemperatureFile->setAutoDefault(false);
        pushButtonTemperatureFile->setFlat(false);
        textLabelRelativeHumidity = new QLabel(tab_1);
        textLabelRelativeHumidity->setObjectName(QStringLiteral("textLabelRelativeHumidity"));
        textLabelRelativeHumidity->setGeometry(QRect(10, 90, 131, 31));
        textLabelPrecipitation = new QLabel(tab_1);
        textLabelPrecipitation->setObjectName(QStringLiteral("textLabelPrecipitation"));
        textLabelPrecipitation->setGeometry(QRect(10, 10, 111, 31));
        lineEditTemperatureFile = new QLineEdit(tab_1);
        lineEditTemperatureFile->setObjectName(QStringLiteral("lineEditTemperatureFile"));
        lineEditTemperatureFile->setGeometry(QRect(163, 51, 301, 29));
        lineEditTemperatureFile->setFont(font1);
        lineEditTemperatureFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelWindVelocity = new QLabel(tab_1);
        textLabelWindVelocity->setObjectName(QStringLiteral("textLabelWindVelocity"));
        textLabelWindVelocity->setGeometry(QRect(10, 131, 121, 31));
        checkBoxPrecipitation = new QCheckBox(tab_1);
        checkBoxPrecipitation->setObjectName(QStringLiteral("checkBoxPrecipitation"));
        checkBoxPrecipitation->setGeometry(QRect(141, 14, 16, 23));
        checkBoxTemperature = new QCheckBox(tab_1);
        checkBoxTemperature->setObjectName(QStringLiteral("checkBoxTemperature"));
        checkBoxTemperature->setGeometry(QRect(141, 53, 16, 23));
        checkBoxRelativeHumidity = new QCheckBox(tab_1);
        checkBoxRelativeHumidity->setObjectName(QStringLiteral("checkBoxRelativeHumidity"));
        checkBoxRelativeHumidity->setGeometry(QRect(141, 94, 16, 23));
        checkBoxWindVelocity = new QCheckBox(tab_1);
        checkBoxWindVelocity->setObjectName(QStringLiteral("checkBoxWindVelocity"));
        checkBoxWindVelocity->setGeometry(QRect(141, 135, 16, 23));
        checkBoxSolarRadiation = new QCheckBox(tab_1);
        checkBoxSolarRadiation->setObjectName(QStringLiteral("checkBoxSolarRadiation"));
        checkBoxSolarRadiation->setGeometry(QRect(141, 175, 16, 23));
        checkBoxVaporPressure = new QCheckBox(tab_1);
        checkBoxVaporPressure->setObjectName(QStringLiteral("checkBoxVaporPressure"));
        checkBoxVaporPressure->setGeometry(QRect(141, 215, 16, 23));
        tabWidget->addTab(tab_1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        textLabelGeologyClasses = new QLabel(tab_2);
        textLabelGeologyClasses->setObjectName(QStringLiteral("textLabelGeologyClasses"));
        textLabelGeologyClasses->setGeometry(QRect(10, 50, 121, 31));
        textLabelSoilClasses = new QLabel(tab_2);
        textLabelSoilClasses->setObjectName(QStringLiteral("textLabelSoilClasses"));
        textLabelSoilClasses->setGeometry(QRect(10, 10, 111, 31));
        pushButtonGeologyClassesFile = new QPushButton(tab_2);
        pushButtonGeologyClassesFile->setObjectName(QStringLiteral("pushButtonGeologyClassesFile"));
        pushButtonGeologyClassesFile->setGeometry(QRect(469, 50, 98, 32));
        pushButtonGeologyClassesFile->setCheckable(false);
        pushButtonGeologyClassesFile->setAutoDefault(false);
        pushButtonGeologyClassesFile->setFlat(false);
        lineEditMacroporesFile = new QLineEdit(tab_2);
        lineEditMacroporesFile->setObjectName(QStringLiteral("lineEditMacroporesFile"));
        lineEditMacroporesFile->setGeometry(QRect(163, 91, 301, 29));
        lineEditMacroporesFile->setFont(font1);
        lineEditMacroporesFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelLandCoverClasses = new QLabel(tab_2);
        textLabelLandCoverClasses->setObjectName(QStringLiteral("textLabelLandCoverClasses"));
        textLabelLandCoverClasses->setGeometry(QRect(10, 131, 131, 31));
        pushButtonLandCoverClassesFile = new QPushButton(tab_2);
        pushButtonLandCoverClassesFile->setObjectName(QStringLiteral("pushButtonLandCoverClassesFile"));
        pushButtonLandCoverClassesFile->setGeometry(QRect(469, 131, 98, 32));
        pushButtonLandCoverClassesFile->setCheckable(false);
        pushButtonLandCoverClassesFile->setAutoDefault(false);
        pushButtonLandCoverClassesFile->setFlat(false);
        lineEditSoilClassesFile = new QLineEdit(tab_2);
        lineEditSoilClassesFile->setObjectName(QStringLiteral("lineEditSoilClassesFile"));
        lineEditSoilClassesFile->setGeometry(QRect(163, 11, 301, 29));
        lineEditSoilClassesFile->setFont(font1);
        lineEditSoilClassesFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonMeltRegionsFile = new QPushButton(tab_2);
        pushButtonMeltRegionsFile->setObjectName(QStringLiteral("pushButtonMeltRegionsFile"));
        pushButtonMeltRegionsFile->setGeometry(QRect(469, 171, 98, 32));
        pushButtonMeltRegionsFile->setCheckable(false);
        pushButtonMeltRegionsFile->setAutoDefault(false);
        pushButtonMeltRegionsFile->setFlat(false);
        textLabelMacropores = new QLabel(tab_2);
        textLabelMacropores->setObjectName(QStringLiteral("textLabelMacropores"));
        textLabelMacropores->setGeometry(QRect(10, 90, 111, 31));
        textLabelMeltRegions = new QLabel(tab_2);
        textLabelMeltRegions->setObjectName(QStringLiteral("textLabelMeltRegions"));
        textLabelMeltRegions->setGeometry(QRect(10, 171, 111, 31));
        lineEditGeologyClassesFile = new QLineEdit(tab_2);
        lineEditGeologyClassesFile->setObjectName(QStringLiteral("lineEditGeologyClassesFile"));
        lineEditGeologyClassesFile->setGeometry(QRect(163, 51, 301, 29));
        lineEditGeologyClassesFile->setFont(font1);
        lineEditGeologyClassesFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditMeltRegionsFile = new QLineEdit(tab_2);
        lineEditMeltRegionsFile->setObjectName(QStringLiteral("lineEditMeltRegionsFile"));
        lineEditMeltRegionsFile->setGeometry(QRect(163, 172, 301, 29));
        lineEditMeltRegionsFile->setFont(font1);
        lineEditMeltRegionsFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonSoilClassesFile = new QPushButton(tab_2);
        pushButtonSoilClassesFile->setObjectName(QStringLiteral("pushButtonSoilClassesFile"));
        pushButtonSoilClassesFile->setGeometry(QRect(469, 10, 98, 32));
        pushButtonSoilClassesFile->setCheckable(false);
        pushButtonSoilClassesFile->setAutoDefault(false);
        pushButtonSoilClassesFile->setFlat(false);
        pushButtonMacroporesFile = new QPushButton(tab_2);
        pushButtonMacroporesFile->setObjectName(QStringLiteral("pushButtonMacroporesFile"));
        pushButtonMacroporesFile->setGeometry(QRect(469, 90, 98, 32));
        pushButtonMacroporesFile->setCheckable(false);
        pushButtonMacroporesFile->setAutoDefault(false);
        pushButtonMacroporesFile->setFlat(false);
        lineEditLandCoverClassesFile = new QLineEdit(tab_2);
        lineEditLandCoverClassesFile->setObjectName(QStringLiteral("lineEditLandCoverClassesFile"));
        lineEditLandCoverClassesFile->setGeometry(QRect(163, 132, 301, 29));
        lineEditLandCoverClassesFile->setFont(font1);
        lineEditLandCoverClassesFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditSourcesSinksFile = new QLineEdit(tab_2);
        lineEditSourcesSinksFile->setObjectName(QStringLiteral("lineEditSourcesSinksFile"));
        lineEditSourcesSinksFile->setGeometry(QRect(163, 212, 301, 29));
        lineEditSourcesSinksFile->setFont(font1);
        lineEditSourcesSinksFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelSourcesSinks = new QLabel(tab_2);
        textLabelSourcesSinks->setObjectName(QStringLiteral("textLabelSourcesSinks"));
        textLabelSourcesSinks->setGeometry(QRect(10, 211, 121, 31));
        pushButtonSourcesSinksFile = new QPushButton(tab_2);
        pushButtonSourcesSinksFile->setObjectName(QStringLiteral("pushButtonSourcesSinksFile"));
        pushButtonSourcesSinksFile->setGeometry(QRect(469, 211, 98, 32));
        pushButtonSourcesSinksFile->setCheckable(false);
        pushButtonSourcesSinksFile->setAutoDefault(false);
        pushButtonSourcesSinksFile->setFlat(false);
        checkBoxSoilClasses = new QCheckBox(tab_2);
        checkBoxSoilClasses->setObjectName(QStringLiteral("checkBoxSoilClasses"));
        checkBoxSoilClasses->setGeometry(QRect(141, 14, 16, 23));
        checkBoxGeologyClasses = new QCheckBox(tab_2);
        checkBoxGeologyClasses->setObjectName(QStringLiteral("checkBoxGeologyClasses"));
        checkBoxGeologyClasses->setGeometry(QRect(141, 53, 16, 23));
        checkBoxMacropores = new QCheckBox(tab_2);
        checkBoxMacropores->setObjectName(QStringLiteral("checkBoxMacropores"));
        checkBoxMacropores->setGeometry(QRect(141, 94, 16, 23));
        checkBoxLandCoverClasses = new QCheckBox(tab_2);
        checkBoxLandCoverClasses->setObjectName(QStringLiteral("checkBoxLandCoverClasses"));
        checkBoxLandCoverClasses->setGeometry(QRect(141, 135, 16, 23));
        checkBoxMeltRegions = new QCheckBox(tab_2);
        checkBoxMeltRegions->setObjectName(QStringLiteral("checkBoxMeltRegions"));
        checkBoxMeltRegions->setGeometry(QRect(141, 175, 16, 23));
        checkBoxSourcesSinks = new QCheckBox(tab_2);
        checkBoxSourcesSinks->setObjectName(QStringLiteral("checkBoxSourcesSinks"));
        checkBoxSourcesSinks->setGeometry(QRect(141, 215, 16, 23));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        textLabelSoilMoisture = new QLabel(tab_3);
        textLabelSoilMoisture->setObjectName(QStringLiteral("textLabelSoilMoisture"));
        textLabelSoilMoisture->setGeometry(QRect(10, 131, 121, 31));
        textLabelBoundaryCondition = new QLabel(tab_3);
        textLabelBoundaryCondition->setObjectName(QStringLiteral("textLabelBoundaryCondition"));
        textLabelBoundaryCondition->setGeometry(QRect(10, 211, 131, 31));
        lineEditInterceptionFile = new QLineEdit(tab_3);
        lineEditInterceptionFile->setObjectName(QStringLiteral("lineEditInterceptionFile"));
        lineEditInterceptionFile->setGeometry(QRect(163, 11, 301, 29));
        lineEditInterceptionFile->setFont(font1);
        lineEditInterceptionFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditSurfaceStorageFile = new QLineEdit(tab_3);
        lineEditSurfaceStorageFile->setObjectName(QStringLiteral("lineEditSurfaceStorageFile"));
        lineEditSurfaceStorageFile->setGeometry(QRect(163, 91, 301, 29));
        lineEditSurfaceStorageFile->setFont(font1);
        lineEditSurfaceStorageFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonSnowCoverFile = new QPushButton(tab_3);
        pushButtonSnowCoverFile->setObjectName(QStringLiteral("pushButtonSnowCoverFile"));
        pushButtonSnowCoverFile->setGeometry(QRect(469, 50, 98, 32));
        pushButtonSnowCoverFile->setCheckable(false);
        pushButtonSnowCoverFile->setAutoDefault(false);
        pushButtonSnowCoverFile->setFlat(false);
        textLabelGroundwater = new QLabel(tab_3);
        textLabelGroundwater->setObjectName(QStringLiteral("textLabelGroundwater"));
        textLabelGroundwater->setGeometry(QRect(10, 171, 121, 31));
        pushButtonGroundwaterFile = new QPushButton(tab_3);
        pushButtonGroundwaterFile->setObjectName(QStringLiteral("pushButtonGroundwaterFile"));
        pushButtonGroundwaterFile->setGeometry(QRect(469, 171, 98, 32));
        pushButtonGroundwaterFile->setCheckable(false);
        pushButtonGroundwaterFile->setAutoDefault(false);
        pushButtonGroundwaterFile->setFlat(false);
        pushButtonBoundaryConditionFile = new QPushButton(tab_3);
        pushButtonBoundaryConditionFile->setObjectName(QStringLiteral("pushButtonBoundaryConditionFile"));
        pushButtonBoundaryConditionFile->setGeometry(QRect(469, 211, 98, 32));
        pushButtonBoundaryConditionFile->setCheckable(false);
        pushButtonBoundaryConditionFile->setAutoDefault(false);
        pushButtonBoundaryConditionFile->setFlat(false);
        lineEditBoundaryConditionFile = new QLineEdit(tab_3);
        lineEditBoundaryConditionFile->setObjectName(QStringLiteral("lineEditBoundaryConditionFile"));
        lineEditBoundaryConditionFile->setGeometry(QRect(163, 212, 301, 29));
        lineEditBoundaryConditionFile->setFont(font1);
        lineEditBoundaryConditionFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditSnowCoverFile = new QLineEdit(tab_3);
        lineEditSnowCoverFile->setObjectName(QStringLiteral("lineEditSnowCoverFile"));
        lineEditSnowCoverFile->setGeometry(QRect(163, 51, 301, 29));
        lineEditSnowCoverFile->setFont(font1);
        lineEditSnowCoverFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pushButtonSurfaceStorageFile = new QPushButton(tab_3);
        pushButtonSurfaceStorageFile->setObjectName(QStringLiteral("pushButtonSurfaceStorageFile"));
        pushButtonSurfaceStorageFile->setGeometry(QRect(469, 90, 98, 32));
        pushButtonSurfaceStorageFile->setCheckable(false);
        pushButtonSurfaceStorageFile->setAutoDefault(false);
        pushButtonSurfaceStorageFile->setFlat(false);
        pushButtonInterceptionFile = new QPushButton(tab_3);
        pushButtonInterceptionFile->setObjectName(QStringLiteral("pushButtonInterceptionFile"));
        pushButtonInterceptionFile->setGeometry(QRect(469, 10, 98, 32));
        pushButtonInterceptionFile->setCheckable(false);
        pushButtonInterceptionFile->setAutoDefault(false);
        pushButtonInterceptionFile->setFlat(false);
        pushButtonSoilMoistureFile = new QPushButton(tab_3);
        pushButtonSoilMoistureFile->setObjectName(QStringLiteral("pushButtonSoilMoistureFile"));
        pushButtonSoilMoistureFile->setGeometry(QRect(469, 131, 98, 32));
        pushButtonSoilMoistureFile->setCheckable(false);
        pushButtonSoilMoistureFile->setAutoDefault(false);
        pushButtonSoilMoistureFile->setFlat(false);
        textLabelSnowCover = new QLabel(tab_3);
        textLabelSnowCover->setObjectName(QStringLiteral("textLabelSnowCover"));
        textLabelSnowCover->setGeometry(QRect(10, 50, 121, 31));
        lineEditGroundwaterFile = new QLineEdit(tab_3);
        lineEditGroundwaterFile->setObjectName(QStringLiteral("lineEditGroundwaterFile"));
        lineEditGroundwaterFile->setGeometry(QRect(163, 172, 301, 29));
        lineEditGroundwaterFile->setFont(font1);
        lineEditGroundwaterFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEditSoilMoistureFile = new QLineEdit(tab_3);
        lineEditSoilMoistureFile->setObjectName(QStringLiteral("lineEditSoilMoistureFile"));
        lineEditSoilMoistureFile->setGeometry(QRect(163, 132, 301, 29));
        lineEditSoilMoistureFile->setFont(font1);
        lineEditSoilMoistureFile->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        textLabelInterception = new QLabel(tab_3);
        textLabelInterception->setObjectName(QStringLiteral("textLabelInterception"));
        textLabelInterception->setGeometry(QRect(10, 10, 121, 31));
        textLabelSurfaceStorage = new QLabel(tab_3);
        textLabelSurfaceStorage->setObjectName(QStringLiteral("textLabelSurfaceStorage"));
        textLabelSurfaceStorage->setGeometry(QRect(10, 90, 131, 31));
        checkBoxSurfaceStorage = new QCheckBox(tab_3);
        checkBoxSurfaceStorage->setObjectName(QStringLiteral("checkBoxSurfaceStorage"));
        checkBoxSurfaceStorage->setGeometry(QRect(141, 94, 16, 23));
        checkBoxInterception = new QCheckBox(tab_3);
        checkBoxInterception->setObjectName(QStringLiteral("checkBoxInterception"));
        checkBoxInterception->setGeometry(QRect(141, 14, 16, 23));
        checkBoxSnowCover = new QCheckBox(tab_3);
        checkBoxSnowCover->setObjectName(QStringLiteral("checkBoxSnowCover"));
        checkBoxSnowCover->setGeometry(QRect(141, 53, 16, 23));
        checkBoxSoilMoisture = new QCheckBox(tab_3);
        checkBoxSoilMoisture->setObjectName(QStringLiteral("checkBoxSoilMoisture"));
        checkBoxSoilMoisture->setGeometry(QRect(141, 135, 16, 23));
        checkBoxGroundwater = new QCheckBox(tab_3);
        checkBoxGroundwater->setObjectName(QStringLiteral("checkBoxGroundwater"));
        checkBoxGroundwater->setGeometry(QRect(141, 175, 16, 23));
        checkBoxBoundaryCondition = new QCheckBox(tab_3);
        checkBoxBoundaryCondition->setObjectName(QStringLiteral("checkBoxBoundaryCondition"));
        checkBoxBoundaryCondition->setGeometry(QRect(141, 215, 16, 23));
        tabWidget->addTab(tab_3, QString());
        groupBoxOutput = new QGroupBox(AttDataFile);
        groupBoxOutput->setObjectName(QStringLiteral("groupBoxOutput"));
        groupBoxOutput->setGeometry(QRect(16, 310, 581, 56));
        textLabel1_7 = new QLabel(groupBoxOutput);
        textLabel1_7->setObjectName(QStringLiteral("textLabel1_7"));
        textLabel1_7->setGeometry(QRect(16, 13, 131, 31));
        pushButtonTINShapeLayerFile = new QPushButton(groupBoxOutput);
        pushButtonTINShapeLayerFile->setObjectName(QStringLiteral("pushButtonTINShapeLayerFile"));
        pushButtonTINShapeLayerFile->setGeometry(QRect(475, 13, 98, 32));
        pushButtonTINShapeLayerFile->setAutoDefault(false);
        lineEditTINShapeLayerFile = new QLineEdit(groupBoxOutput);
        lineEditTINShapeLayerFile->setObjectName(QStringLiteral("lineEditTINShapeLayerFile"));
        lineEditTINShapeLayerFile->setGeometry(QRect(145, 14, 325, 29));
        lineEditTINShapeLayerFile->setFont(font1);
        groupBoxOutput_2 = new QGroupBox(AttDataFile);
        groupBoxOutput_2->setObjectName(QStringLiteral("groupBoxOutput_2"));
        groupBoxOutput_2->setGeometry(QRect(15, 366, 581, 85));
        textLabel1_8 = new QLabel(groupBoxOutput_2);
        textLabel1_8->setObjectName(QStringLiteral("textLabel1_8"));
        textLabel1_8->setGeometry(QRect(16, 37, 131, 31));
        pushButtonAttDataFile = new QPushButton(groupBoxOutput_2);
        pushButtonAttDataFile->setObjectName(QStringLiteral("pushButtonAttDataFile"));
        pushButtonAttDataFile->setGeometry(QRect(475, 37, 98, 32));
        pushButtonAttDataFile->setAutoDefault(false);
        lineEditAttDataFile = new QLineEdit(groupBoxOutput_2);
        lineEditAttDataFile->setObjectName(QStringLiteral("lineEditAttDataFile"));
        lineEditAttDataFile->setGeometry(QRect(145, 38, 325, 29));
        lineEditAttDataFile->setFont(font1);

        retranslateUi(AttDataFile);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(AttDataFile);
    } // setupUi

    void retranslateUi(QDialog *AttDataFile)
    {
        AttDataFile->setWindowTitle(QApplication::translate("AttDataFile", ": :   Att Data File   : :", 0));
        groupBoxButtons->setTitle(QString());
        pushButtonHelp->setText(QApplication::translate("AttDataFile", "Help", 0));
        pushButtonClose->setText(QApplication::translate("AttDataFile", "Close", 0));
#ifndef QT_NO_TOOLTIP
        pushButtonRun->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pushButtonRun->setText(QApplication::translate("AttDataFile", "Run", 0));
        textLabelLegends1->setText(QApplication::translate("AttDataFile", "<html><head/><body><p><span style=\" vertical-align:super;\">1 </span>Homogeneous Class</p></body></html>", 0));
        textLabelLegends2->setText(QApplication::translate("AttDataFile", "<html><head/><body><p><span style=\" vertical-align:super;\">2 </span>Classification Raster Layer</p></body></html>", 0));
        textLabelLegends3->setText(QApplication::translate("AttDataFile", "<html><head/><body><p><span style=\" vertical-align:super;\">3 </span>Parameter Value / Raster Layer</p></body></html>", 0));
        pushButtonWindVelocityFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonVaporPressureFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelTemperature->setText(QApplication::translate("AttDataFile", "Temperature", 0));
        pushButtonPrecipitationFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonRelativeHumidityFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelVaporPressure->setText(QApplication::translate("AttDataFile", "Vapor Pressure", 0));
        pushButtonSolarRadiationFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelSolarRadiation->setText(QApplication::translate("AttDataFile", "Solar Radiation", 0));
        pushButtonTemperatureFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelRelativeHumidity->setText(QApplication::translate("AttDataFile", "Relative Humidity", 0));
        textLabelPrecipitation->setText(QApplication::translate("AttDataFile", "Precipitation", 0));
        textLabelWindVelocity->setText(QApplication::translate("AttDataFile", "Wind Velocity", 0));
        checkBoxPrecipitation->setText(QString());
        checkBoxTemperature->setText(QString());
        checkBoxRelativeHumidity->setText(QString());
        checkBoxWindVelocity->setText(QString());
        checkBoxSolarRadiation->setText(QString());
        checkBoxVaporPressure->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_1), QApplication::translate("AttDataFile", "  Climate Classifications  ", 0));
        textLabelGeologyClasses->setText(QApplication::translate("AttDataFile", "Geology Classes", 0));
        textLabelSoilClasses->setText(QApplication::translate("AttDataFile", "Soil Classes", 0));
        pushButtonGeologyClassesFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelLandCoverClasses->setText(QApplication::translate("AttDataFile", "Land Cover Classes", 0));
        pushButtonLandCoverClassesFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonMeltRegionsFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelMacropores->setText(QApplication::translate("AttDataFile", "Macropores", 0));
        textLabelMeltRegions->setText(QApplication::translate("AttDataFile", "Melt Regions", 0));
        pushButtonSoilClassesFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonMacroporesFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelSourcesSinks->setText(QApplication::translate("AttDataFile", "Sources / Sinks", 0));
        pushButtonSourcesSinksFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        checkBoxSoilClasses->setText(QString());
        checkBoxGeologyClasses->setText(QString());
        checkBoxMacropores->setText(QString());
        checkBoxLandCoverClasses->setText(QString());
        checkBoxMeltRegions->setText(QString());
        checkBoxSourcesSinks->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("AttDataFile", " Soil, Geology, Land Cover ", 0));
        textLabelSoilMoisture->setText(QApplication::translate("AttDataFile", "Soil Moisture (m)", 0));
        textLabelBoundaryCondition->setText(QApplication::translate("AttDataFile", "Boundary Condition", 0));
        pushButtonSnowCoverFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelGroundwater->setText(QApplication::translate("AttDataFile", "Groundwater (m)", 0));
        pushButtonGroundwaterFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonBoundaryConditionFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonSurfaceStorageFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonInterceptionFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        pushButtonSoilMoistureFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        textLabelSnowCover->setText(QApplication::translate("AttDataFile", "Snow Cover (m)", 0));
        textLabelInterception->setText(QApplication::translate("AttDataFile", "Interception (m)", 0));
        textLabelSurfaceStorage->setText(QApplication::translate("AttDataFile", "Surface water (m)", 0));
        checkBoxSurfaceStorage->setText(QString());
        checkBoxInterception->setText(QString());
        checkBoxSnowCover->setText(QString());
        checkBoxSoilMoisture->setText(QString());
        checkBoxGroundwater->setText(QString());
        checkBoxBoundaryCondition->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("AttDataFile", "Initial / Boundary Conditions", 0));
        groupBoxOutput->setTitle(QString());
        textLabel1_7->setText(QApplication::translate("AttDataFile", "TIN Shape Layer", 0));
        pushButtonTINShapeLayerFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
        groupBoxOutput_2->setTitle(QApplication::translate("AttDataFile", "Output", 0));
        textLabel1_8->setText(QApplication::translate("AttDataFile", "Att Data File", 0));
        pushButtonAttDataFile->setText(QApplication::translate("AttDataFile", "Browse", 0));
    } // retranslateUi

};

namespace Ui {
    class AttDataFile: public Ui_AttDataFile {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ATTDATAFILE_H
