/********************************************************************************
** Form generated from reading UI file 'calibdatafile.ui'
**
** Created by: Qt User Interface Compiler version 5.1.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CALIBDATAFILE_H
#define UI_CALIBDATAFILE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CalibDataFile
{
public:
    QFrame *BorderTop;
    QTextBrowser *textBrowserLogs;
    QFrame *BorderBottom;
    QGroupBox *groupBoxButtons;
    QPushButton *pushButtonHelp;
    QPushButton *pushButtonClose;
    QPushButton *pushButtonRun;
    QGroupBox *groupBoxOutput;
    QLabel *textLabelPara;
    QPushButton *pushButtonCalibDataFile;
    QLineEdit *lineEditCalibDataFile;
    QTabWidget *tabWidget;
    QWidget *tab_1;
    QDoubleSpinBox *doubleSpinBoxS_Beta;
    QLabel *textLabel1_20;
    QLabel *textLabel1_21;
    QLabel *textLabel1_22;
    QDoubleSpinBox *doubleSpinBoxS_KsatV;
    QDoubleSpinBox *doubleSpinBoxS_Porosity;
    QDoubleSpinBox *doubleSpinBoxS_MPKsatV;
    QLabel *textLabel1_23;
    QLabel *textLabel1_24;
    QDoubleSpinBox *doubleSpinBoxS_InfilDepth;
    QLabel *textLabel1_25;
    QDoubleSpinBox *doubleSpinBoxS_Alpha;
    QWidget *tab_2;
    QDoubleSpinBox *doubleSpinBoxG_KsatV;
    QLabel *textLabel1_6;
    QLabel *textLabel1_8;
    QDoubleSpinBox *doubleSpinBoxG_KsatH;
    QDoubleSpinBox *doubleSpinBoxG_MPDepth;
    QLabel *textLabel1_9;
    QLabel *textLabel1_7;
    QDoubleSpinBox *doubleSpinBoxG_MPKsatH;
    QLabel *textLabel1_10;
    QDoubleSpinBox *doubleSpinBoxG_MPfracV;
    QLabel *textLabel1_19;
    QDoubleSpinBox *doubleSpinBoxG_MPfracH;
    QWidget *tab_3;
    QDoubleSpinBox *doubleSpinBoxL_VegFrac;
    QLabel *textLabel1_29;
    QDoubleSpinBox *doubleSpinBoxL_Albedo;
    QLabel *textLabel1_30;
    QLabel *textLabel1_31;
    QDoubleSpinBox *doubleSpinBoxL_Roughness;
    QLabel *textLabel1_32;
    QDoubleSpinBox *doubleSpinBoxL_RZDepth;
    QWidget *tab_4;
    QDoubleSpinBox *doubleSpinBoxR_BedTh;
    QLabel *textLabel1_13;
    QDoubleSpinBox *doubleSpinBoxR_KsatH;
    QLabel *textLabel1_14;
    QLabel *textLabel1_15;
    QDoubleSpinBox *doubleSpinBoxR_KsatV;
    QLabel *textLabel1_16;
    QDoubleSpinBox *doubleSpinBoxR_Rough;
    QLabel *textLabel1_17;
    QDoubleSpinBox *doubleSpinBoxR_Width;
    QLabel *textLabel1_18;
    QDoubleSpinBox *doubleSpinBoxR_Depth;
    QWidget *tab_5;
    QLabel *textLabel1_11;
    QDoubleSpinBox *doubleSpinBoxF_Temp;
    QLabel *textLabel1_12;
    QDoubleSpinBox *doubleSpinBoxF_Precip;
    QDoubleSpinBox *doubleSpinBoxF_ET2;
    QDoubleSpinBox *doubleSpinBoxF_ET1;
    QDoubleSpinBox *doubleSpinBoxF_ET0;
    QLabel *textLabel1_26;
    QLabel *textLabel1_27;
    QLabel *textLabel1_28;
    QDoubleSpinBox *doubleSpinBoxF_ISMax;
    QDoubleSpinBox *doubleSpinBoxF_ThruFall;
    QLabel *textLabel1_33;
    QLabel *textLabel1_34;
    QDoubleSpinBox *doubleSpinBoxF_MeltFac;
    QLabel *textLabel1_35;

    void setupUi(QDialog *CalibDataFile)
    {
        if (CalibDataFile->objectName().isEmpty())
            CalibDataFile->setObjectName(QStringLiteral("CalibDataFile"));
        CalibDataFile->resize(611, 455);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        CalibDataFile->setPalette(palette);
        BorderTop = new QFrame(CalibDataFile);
        BorderTop->setObjectName(QStringLiteral("BorderTop"));
        BorderTop->setGeometry(QRect(0, -4, 611, 20));
        BorderTop->setBaseSize(QSize(0, 0));
        QPalette palette1;
        QBrush brush5(QColor(0, 51, 153, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        QBrush brush6(QColor(128, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush6);
        QBrush brush7(QColor(192, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush7);
        QBrush brush8(QColor(160, 0, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        QBrush brush9(QColor(64, 0, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush9);
        QBrush brush10(QColor(85, 0, 0, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderTop->setPalette(palette1);
        BorderTop->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderTop->setFrameShadow(QFrame::Plain);
        BorderTop->setLineWidth(12);
        BorderTop->setMidLineWidth(0);
        BorderTop->setFrameShape(QFrame::HLine);
        textBrowserLogs = new QTextBrowser(CalibDataFile);
        textBrowserLogs->setObjectName(QStringLiteral("textBrowserLogs"));
        textBrowserLogs->setGeometry(QRect(15, 364, 581, 71));
        textBrowserLogs->setLineWrapMode(QTextEdit::NoWrap);
        BorderBottom = new QFrame(CalibDataFile);
        BorderBottom->setObjectName(QStringLiteral("BorderBottom"));
        BorderBottom->setGeometry(QRect(0, 439, 611, 20));
        BorderBottom->setBaseSize(QSize(0, 0));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        BorderBottom->setPalette(palette2);
        BorderBottom->setStyleSheet(QStringLiteral("color: rgb(0, 51, 153);"));
        BorderBottom->setFrameShadow(QFrame::Plain);
        BorderBottom->setLineWidth(12);
        BorderBottom->setMidLineWidth(0);
        BorderBottom->setFrameShape(QFrame::HLine);
        groupBoxButtons = new QGroupBox(CalibDataFile);
        groupBoxButtons->setObjectName(QStringLiteral("groupBoxButtons"));
        groupBoxButtons->setGeometry(QRect(15, 292, 581, 61));
        pushButtonHelp = new QPushButton(groupBoxButtons);
        pushButtonHelp->setObjectName(QStringLiteral("pushButtonHelp"));
        pushButtonHelp->setGeometry(QRect(10, 17, 113, 32));
        pushButtonHelp->setAutoDefault(false);
        pushButtonClose = new QPushButton(groupBoxButtons);
        pushButtonClose->setObjectName(QStringLiteral("pushButtonClose"));
        pushButtonClose->setGeometry(QRect(326, 17, 113, 32));
        pushButtonClose->setAutoDefault(false);
        pushButtonRun = new QPushButton(groupBoxButtons);
        pushButtonRun->setObjectName(QStringLiteral("pushButtonRun"));
        pushButtonRun->setGeometry(QRect(460, 17, 113, 32));
        pushButtonRun->setAutoDefault(false);
        groupBoxOutput = new QGroupBox(CalibDataFile);
        groupBoxOutput->setObjectName(QStringLiteral("groupBoxOutput"));
        groupBoxOutput->setGeometry(QRect(15, 189, 581, 91));
        textLabelPara = new QLabel(groupBoxOutput);
        textLabelPara->setObjectName(QStringLiteral("textLabelPara"));
        textLabelPara->setGeometry(QRect(16, 41, 131, 31));
        pushButtonCalibDataFile = new QPushButton(groupBoxOutput);
        pushButtonCalibDataFile->setObjectName(QStringLiteral("pushButtonCalibDataFile"));
        pushButtonCalibDataFile->setGeometry(QRect(475, 41, 98, 32));
        pushButtonCalibDataFile->setAutoDefault(false);
        lineEditCalibDataFile = new QLineEdit(groupBoxOutput);
        lineEditCalibDataFile->setObjectName(QStringLiteral("lineEditCalibDataFile"));
        lineEditCalibDataFile->setGeometry(QRect(145, 42, 325, 29));
        QFont font;
        font.setPointSize(14);
        font.setBold(true);
        font.setWeight(75);
        lineEditCalibDataFile->setFont(font);
        tabWidget = new QTabWidget(CalibDataFile);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(15, 20, 581, 161));
        tab_1 = new QWidget();
        tab_1->setObjectName(QStringLiteral("tab_1"));
        doubleSpinBoxS_Beta = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_Beta->setObjectName(QStringLiteral("doubleSpinBoxS_Beta"));
        doubleSpinBoxS_Beta->setGeometry(QRect(67, 74, 101, 29));
        doubleSpinBoxS_Beta->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_Beta->setDecimals(6);
        doubleSpinBoxS_Beta->setMaximum(99);
        doubleSpinBoxS_Beta->setSingleStep(0.1);
        doubleSpinBoxS_Beta->setValue(1);
        textLabel1_20 = new QLabel(tab_1);
        textLabel1_20->setObjectName(QStringLiteral("textLabel1_20"));
        textLabel1_20->setGeometry(QRect(197, 29, 71, 31));
        textLabel1_21 = new QLabel(tab_1);
        textLabel1_21->setObjectName(QStringLiteral("textLabel1_21"));
        textLabel1_21->setGeometry(QRect(396, 73, 71, 31));
        textLabel1_22 = new QLabel(tab_1);
        textLabel1_22->setObjectName(QStringLiteral("textLabel1_22"));
        textLabel1_22->setGeometry(QRect(396, 29, 71, 31));
        doubleSpinBoxS_KsatV = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_KsatV->setObjectName(QStringLiteral("doubleSpinBoxS_KsatV"));
        doubleSpinBoxS_KsatV->setGeometry(QRect(457, 30, 101, 29));
        doubleSpinBoxS_KsatV->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_KsatV->setDecimals(6);
        doubleSpinBoxS_KsatV->setMaximum(99);
        doubleSpinBoxS_KsatV->setSingleStep(0.1);
        doubleSpinBoxS_KsatV->setValue(1);
        doubleSpinBoxS_Porosity = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_Porosity->setObjectName(QStringLiteral("doubleSpinBoxS_Porosity"));
        doubleSpinBoxS_Porosity->setGeometry(QRect(267, 30, 101, 29));
        doubleSpinBoxS_Porosity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_Porosity->setDecimals(6);
        doubleSpinBoxS_Porosity->setMaximum(99);
        doubleSpinBoxS_Porosity->setSingleStep(0.1);
        doubleSpinBoxS_Porosity->setValue(1);
        doubleSpinBoxS_MPKsatV = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_MPKsatV->setObjectName(QStringLiteral("doubleSpinBoxS_MPKsatV"));
        doubleSpinBoxS_MPKsatV->setGeometry(QRect(457, 74, 101, 29));
        doubleSpinBoxS_MPKsatV->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_MPKsatV->setDecimals(6);
        doubleSpinBoxS_MPKsatV->setMaximum(99);
        doubleSpinBoxS_MPKsatV->setSingleStep(0.1);
        doubleSpinBoxS_MPKsatV->setValue(1);
        textLabel1_23 = new QLabel(tab_1);
        textLabel1_23->setObjectName(QStringLiteral("textLabel1_23"));
        textLabel1_23->setGeometry(QRect(17, 29, 71, 31));
        textLabel1_24 = new QLabel(tab_1);
        textLabel1_24->setObjectName(QStringLiteral("textLabel1_24"));
        textLabel1_24->setGeometry(QRect(17, 73, 71, 31));
        doubleSpinBoxS_InfilDepth = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_InfilDepth->setObjectName(QStringLiteral("doubleSpinBoxS_InfilDepth"));
        doubleSpinBoxS_InfilDepth->setGeometry(QRect(267, 74, 101, 29));
        doubleSpinBoxS_InfilDepth->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_InfilDepth->setDecimals(6);
        doubleSpinBoxS_InfilDepth->setMaximum(99);
        doubleSpinBoxS_InfilDepth->setSingleStep(0.1);
        doubleSpinBoxS_InfilDepth->setValue(1);
        textLabel1_25 = new QLabel(tab_1);
        textLabel1_25->setObjectName(QStringLiteral("textLabel1_25"));
        textLabel1_25->setGeometry(QRect(197, 73, 71, 31));
        doubleSpinBoxS_Alpha = new QDoubleSpinBox(tab_1);
        doubleSpinBoxS_Alpha->setObjectName(QStringLiteral("doubleSpinBoxS_Alpha"));
        doubleSpinBoxS_Alpha->setGeometry(QRect(67, 30, 101, 29));
        doubleSpinBoxS_Alpha->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxS_Alpha->setDecimals(6);
        doubleSpinBoxS_Alpha->setMaximum(99);
        doubleSpinBoxS_Alpha->setSingleStep(0.1);
        doubleSpinBoxS_Alpha->setValue(1);
        tabWidget->addTab(tab_1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        doubleSpinBoxG_KsatV = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_KsatV->setObjectName(QStringLiteral("doubleSpinBoxG_KsatV"));
        doubleSpinBoxG_KsatV->setGeometry(QRect(68, 75, 101, 29));
        doubleSpinBoxG_KsatV->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_KsatV->setDecimals(6);
        doubleSpinBoxG_KsatV->setMaximum(99);
        doubleSpinBoxG_KsatV->setSingleStep(0.1);
        doubleSpinBoxG_KsatV->setValue(1);
        textLabel1_6 = new QLabel(tab_2);
        textLabel1_6->setObjectName(QStringLiteral("textLabel1_6"));
        textLabel1_6->setGeometry(QRect(18, 74, 71, 31));
        textLabel1_8 = new QLabel(tab_2);
        textLabel1_8->setObjectName(QStringLiteral("textLabel1_8"));
        textLabel1_8->setGeometry(QRect(18, 30, 71, 31));
        doubleSpinBoxG_KsatH = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_KsatH->setObjectName(QStringLiteral("doubleSpinBoxG_KsatH"));
        doubleSpinBoxG_KsatH->setGeometry(QRect(68, 31, 101, 29));
        doubleSpinBoxG_KsatH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_KsatH->setDecimals(6);
        doubleSpinBoxG_KsatH->setMaximum(99);
        doubleSpinBoxG_KsatH->setSingleStep(0.1);
        doubleSpinBoxG_KsatH->setValue(1);
        doubleSpinBoxG_MPDepth = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_MPDepth->setObjectName(QStringLiteral("doubleSpinBoxG_MPDepth"));
        doubleSpinBoxG_MPDepth->setGeometry(QRect(268, 75, 101, 29));
        doubleSpinBoxG_MPDepth->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_MPDepth->setDecimals(6);
        doubleSpinBoxG_MPDepth->setMaximum(99);
        doubleSpinBoxG_MPDepth->setSingleStep(0.1);
        doubleSpinBoxG_MPDepth->setValue(1);
        textLabel1_9 = new QLabel(tab_2);
        textLabel1_9->setObjectName(QStringLiteral("textLabel1_9"));
        textLabel1_9->setGeometry(QRect(198, 30, 71, 31));
        textLabel1_7 = new QLabel(tab_2);
        textLabel1_7->setObjectName(QStringLiteral("textLabel1_7"));
        textLabel1_7->setGeometry(QRect(198, 74, 71, 31));
        doubleSpinBoxG_MPKsatH = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_MPKsatH->setObjectName(QStringLiteral("doubleSpinBoxG_MPKsatH"));
        doubleSpinBoxG_MPKsatH->setGeometry(QRect(268, 31, 101, 29));
        doubleSpinBoxG_MPKsatH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_MPKsatH->setDecimals(6);
        doubleSpinBoxG_MPKsatH->setMaximum(99);
        doubleSpinBoxG_MPKsatH->setSingleStep(0.1);
        doubleSpinBoxG_MPKsatH->setValue(1);
        textLabel1_10 = new QLabel(tab_2);
        textLabel1_10->setObjectName(QStringLiteral("textLabel1_10"));
        textLabel1_10->setGeometry(QRect(398, 30, 71, 31));
        doubleSpinBoxG_MPfracV = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_MPfracV->setObjectName(QStringLiteral("doubleSpinBoxG_MPfracV"));
        doubleSpinBoxG_MPfracV->setGeometry(QRect(458, 31, 101, 29));
        doubleSpinBoxG_MPfracV->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_MPfracV->setDecimals(6);
        doubleSpinBoxG_MPfracV->setMaximum(99);
        doubleSpinBoxG_MPfracV->setSingleStep(0.1);
        doubleSpinBoxG_MPfracV->setValue(1);
        textLabel1_19 = new QLabel(tab_2);
        textLabel1_19->setObjectName(QStringLiteral("textLabel1_19"));
        textLabel1_19->setGeometry(QRect(398, 74, 71, 31));
        doubleSpinBoxG_MPfracH = new QDoubleSpinBox(tab_2);
        doubleSpinBoxG_MPfracH->setObjectName(QStringLiteral("doubleSpinBoxG_MPfracH"));
        doubleSpinBoxG_MPfracH->setGeometry(QRect(458, 75, 101, 29));
        doubleSpinBoxG_MPfracH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxG_MPfracH->setDecimals(6);
        doubleSpinBoxG_MPfracH->setMaximum(99);
        doubleSpinBoxG_MPfracH->setSingleStep(0.1);
        doubleSpinBoxG_MPfracH->setValue(1);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        doubleSpinBoxL_VegFrac = new QDoubleSpinBox(tab_3);
        doubleSpinBoxL_VegFrac->setObjectName(QStringLiteral("doubleSpinBoxL_VegFrac"));
        doubleSpinBoxL_VegFrac->setGeometry(QRect(160, 74, 101, 29));
        doubleSpinBoxL_VegFrac->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxL_VegFrac->setDecimals(6);
        doubleSpinBoxL_VegFrac->setMaximum(99);
        doubleSpinBoxL_VegFrac->setSingleStep(0.1);
        doubleSpinBoxL_VegFrac->setValue(1);
        textLabel1_29 = new QLabel(tab_3);
        textLabel1_29->setObjectName(QStringLiteral("textLabel1_29"));
        textLabel1_29->setGeometry(QRect(320, 29, 71, 31));
        doubleSpinBoxL_Albedo = new QDoubleSpinBox(tab_3);
        doubleSpinBoxL_Albedo->setObjectName(QStringLiteral("doubleSpinBoxL_Albedo"));
        doubleSpinBoxL_Albedo->setGeometry(QRect(410, 30, 101, 29));
        doubleSpinBoxL_Albedo->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxL_Albedo->setDecimals(6);
        doubleSpinBoxL_Albedo->setMaximum(99);
        doubleSpinBoxL_Albedo->setSingleStep(0.1);
        doubleSpinBoxL_Albedo->setValue(1);
        textLabel1_30 = new QLabel(tab_3);
        textLabel1_30->setObjectName(QStringLiteral("textLabel1_30"));
        textLabel1_30->setGeometry(QRect(90, 29, 71, 31));
        textLabel1_31 = new QLabel(tab_3);
        textLabel1_31->setObjectName(QStringLiteral("textLabel1_31"));
        textLabel1_31->setGeometry(QRect(90, 73, 71, 31));
        doubleSpinBoxL_Roughness = new QDoubleSpinBox(tab_3);
        doubleSpinBoxL_Roughness->setObjectName(QStringLiteral("doubleSpinBoxL_Roughness"));
        doubleSpinBoxL_Roughness->setGeometry(QRect(410, 74, 101, 29));
        doubleSpinBoxL_Roughness->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxL_Roughness->setDecimals(6);
        doubleSpinBoxL_Roughness->setMaximum(99);
        doubleSpinBoxL_Roughness->setSingleStep(0.1);
        doubleSpinBoxL_Roughness->setValue(1);
        textLabel1_32 = new QLabel(tab_3);
        textLabel1_32->setObjectName(QStringLiteral("textLabel1_32"));
        textLabel1_32->setGeometry(QRect(320, 73, 71, 31));
        doubleSpinBoxL_RZDepth = new QDoubleSpinBox(tab_3);
        doubleSpinBoxL_RZDepth->setObjectName(QStringLiteral("doubleSpinBoxL_RZDepth"));
        doubleSpinBoxL_RZDepth->setGeometry(QRect(160, 30, 101, 29));
        doubleSpinBoxL_RZDepth->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxL_RZDepth->setDecimals(6);
        doubleSpinBoxL_RZDepth->setMaximum(99);
        doubleSpinBoxL_RZDepth->setSingleStep(0.1);
        doubleSpinBoxL_RZDepth->setValue(1);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        doubleSpinBoxR_BedTh = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_BedTh->setObjectName(QStringLiteral("doubleSpinBoxR_BedTh"));
        doubleSpinBoxR_BedTh->setGeometry(QRect(70, 74, 101, 29));
        doubleSpinBoxR_BedTh->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_BedTh->setDecimals(6);
        doubleSpinBoxR_BedTh->setMaximum(99);
        doubleSpinBoxR_BedTh->setSingleStep(0.1);
        doubleSpinBoxR_BedTh->setValue(1);
        textLabel1_13 = new QLabel(tab_4);
        textLabel1_13->setObjectName(QStringLiteral("textLabel1_13"));
        textLabel1_13->setGeometry(QRect(197, 29, 71, 31));
        doubleSpinBoxR_KsatH = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_KsatH->setObjectName(QStringLiteral("doubleSpinBoxR_KsatH"));
        doubleSpinBoxR_KsatH->setGeometry(QRect(267, 30, 101, 29));
        doubleSpinBoxR_KsatH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_KsatH->setDecimals(6);
        doubleSpinBoxR_KsatH->setMaximum(99);
        doubleSpinBoxR_KsatH->setSingleStep(0.1);
        doubleSpinBoxR_KsatH->setValue(1);
        textLabel1_14 = new QLabel(tab_4);
        textLabel1_14->setObjectName(QStringLiteral("textLabel1_14"));
        textLabel1_14->setGeometry(QRect(20, 29, 71, 31));
        textLabel1_15 = new QLabel(tab_4);
        textLabel1_15->setObjectName(QStringLiteral("textLabel1_15"));
        textLabel1_15->setGeometry(QRect(20, 73, 71, 31));
        doubleSpinBoxR_KsatV = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_KsatV->setObjectName(QStringLiteral("doubleSpinBoxR_KsatV"));
        doubleSpinBoxR_KsatV->setGeometry(QRect(267, 74, 101, 29));
        doubleSpinBoxR_KsatV->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_KsatV->setDecimals(6);
        doubleSpinBoxR_KsatV->setMaximum(99);
        doubleSpinBoxR_KsatV->setSingleStep(0.1);
        doubleSpinBoxR_KsatV->setValue(1);
        textLabel1_16 = new QLabel(tab_4);
        textLabel1_16->setObjectName(QStringLiteral("textLabel1_16"));
        textLabel1_16->setGeometry(QRect(197, 73, 71, 31));
        doubleSpinBoxR_Rough = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_Rough->setObjectName(QStringLiteral("doubleSpinBoxR_Rough"));
        doubleSpinBoxR_Rough->setGeometry(QRect(70, 30, 101, 29));
        doubleSpinBoxR_Rough->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_Rough->setDecimals(6);
        doubleSpinBoxR_Rough->setMaximum(99);
        doubleSpinBoxR_Rough->setSingleStep(0.1);
        doubleSpinBoxR_Rough->setValue(1);
        textLabel1_17 = new QLabel(tab_4);
        textLabel1_17->setObjectName(QStringLiteral("textLabel1_17"));
        textLabel1_17->setGeometry(QRect(390, 29, 71, 31));
        doubleSpinBoxR_Width = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_Width->setObjectName(QStringLiteral("doubleSpinBoxR_Width"));
        doubleSpinBoxR_Width->setGeometry(QRect(460, 74, 101, 29));
        doubleSpinBoxR_Width->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_Width->setDecimals(6);
        doubleSpinBoxR_Width->setMaximum(99);
        doubleSpinBoxR_Width->setSingleStep(0.1);
        doubleSpinBoxR_Width->setValue(1);
        textLabel1_18 = new QLabel(tab_4);
        textLabel1_18->setObjectName(QStringLiteral("textLabel1_18"));
        textLabel1_18->setGeometry(QRect(390, 73, 71, 31));
        doubleSpinBoxR_Depth = new QDoubleSpinBox(tab_4);
        doubleSpinBoxR_Depth->setObjectName(QStringLiteral("doubleSpinBoxR_Depth"));
        doubleSpinBoxR_Depth->setGeometry(QRect(460, 30, 101, 29));
        doubleSpinBoxR_Depth->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxR_Depth->setDecimals(6);
        doubleSpinBoxR_Depth->setMaximum(99);
        doubleSpinBoxR_Depth->setSingleStep(0.1);
        doubleSpinBoxR_Depth->setValue(1);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        textLabel1_11 = new QLabel(tab_5);
        textLabel1_11->setObjectName(QStringLiteral("textLabel1_11"));
        textLabel1_11->setGeometry(QRect(300, 8, 71, 31));
        doubleSpinBoxF_Temp = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_Temp->setObjectName(QStringLiteral("doubleSpinBoxF_Temp"));
        doubleSpinBoxF_Temp->setGeometry(QRect(370, 9, 101, 29));
        doubleSpinBoxF_Temp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_Temp->setDecimals(6);
        doubleSpinBoxF_Temp->setMaximum(99);
        doubleSpinBoxF_Temp->setSingleStep(0.1);
        doubleSpinBoxF_Temp->setValue(1);
        textLabel1_12 = new QLabel(tab_5);
        textLabel1_12->setObjectName(QStringLiteral("textLabel1_12"));
        textLabel1_12->setGeometry(QRect(120, 8, 71, 31));
        doubleSpinBoxF_Precip = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_Precip->setObjectName(QStringLiteral("doubleSpinBoxF_Precip"));
        doubleSpinBoxF_Precip->setGeometry(QRect(170, 9, 101, 29));
        doubleSpinBoxF_Precip->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_Precip->setDecimals(6);
        doubleSpinBoxF_Precip->setMaximum(99);
        doubleSpinBoxF_Precip->setSingleStep(0.1);
        doubleSpinBoxF_Precip->setValue(1);
        doubleSpinBoxF_ET2 = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_ET2->setObjectName(QStringLiteral("doubleSpinBoxF_ET2"));
        doubleSpinBoxF_ET2->setGeometry(QRect(460, 50, 101, 29));
        doubleSpinBoxF_ET2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_ET2->setDecimals(6);
        doubleSpinBoxF_ET2->setMaximum(99);
        doubleSpinBoxF_ET2->setSingleStep(0.1);
        doubleSpinBoxF_ET2->setValue(1);
        doubleSpinBoxF_ET1 = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_ET1->setObjectName(QStringLiteral("doubleSpinBoxF_ET1"));
        doubleSpinBoxF_ET1->setGeometry(QRect(270, 50, 101, 29));
        doubleSpinBoxF_ET1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_ET1->setDecimals(6);
        doubleSpinBoxF_ET1->setMaximum(99);
        doubleSpinBoxF_ET1->setSingleStep(0.1);
        doubleSpinBoxF_ET1->setValue(1);
        doubleSpinBoxF_ET0 = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_ET0->setObjectName(QStringLiteral("doubleSpinBoxF_ET0"));
        doubleSpinBoxF_ET0->setGeometry(QRect(70, 50, 101, 29));
        doubleSpinBoxF_ET0->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_ET0->setDecimals(6);
        doubleSpinBoxF_ET0->setMaximum(99);
        doubleSpinBoxF_ET0->setSingleStep(0.1);
        doubleSpinBoxF_ET0->setValue(1);
        textLabel1_26 = new QLabel(tab_5);
        textLabel1_26->setObjectName(QStringLiteral("textLabel1_26"));
        textLabel1_26->setGeometry(QRect(200, 49, 71, 31));
        textLabel1_27 = new QLabel(tab_5);
        textLabel1_27->setObjectName(QStringLiteral("textLabel1_27"));
        textLabel1_27->setGeometry(QRect(399, 49, 71, 31));
        textLabel1_28 = new QLabel(tab_5);
        textLabel1_28->setObjectName(QStringLiteral("textLabel1_28"));
        textLabel1_28->setGeometry(QRect(20, 45, 71, 41));
        doubleSpinBoxF_ISMax = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_ISMax->setObjectName(QStringLiteral("doubleSpinBoxF_ISMax"));
        doubleSpinBoxF_ISMax->setGeometry(QRect(70, 93, 101, 29));
        doubleSpinBoxF_ISMax->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_ISMax->setDecimals(6);
        doubleSpinBoxF_ISMax->setMaximum(99);
        doubleSpinBoxF_ISMax->setSingleStep(0.1);
        doubleSpinBoxF_ISMax->setValue(1);
        doubleSpinBoxF_ThruFall = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_ThruFall->setObjectName(QStringLiteral("doubleSpinBoxF_ThruFall"));
        doubleSpinBoxF_ThruFall->setGeometry(QRect(270, 93, 101, 29));
        doubleSpinBoxF_ThruFall->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_ThruFall->setDecimals(6);
        doubleSpinBoxF_ThruFall->setMaximum(99);
        doubleSpinBoxF_ThruFall->setSingleStep(0.1);
        doubleSpinBoxF_ThruFall->setValue(1);
        textLabel1_33 = new QLabel(tab_5);
        textLabel1_33->setObjectName(QStringLiteral("textLabel1_33"));
        textLabel1_33->setGeometry(QRect(399, 92, 71, 31));
        textLabel1_34 = new QLabel(tab_5);
        textLabel1_34->setObjectName(QStringLiteral("textLabel1_34"));
        textLabel1_34->setGeometry(QRect(20, 88, 71, 41));
        doubleSpinBoxF_MeltFac = new QDoubleSpinBox(tab_5);
        doubleSpinBoxF_MeltFac->setObjectName(QStringLiteral("doubleSpinBoxF_MeltFac"));
        doubleSpinBoxF_MeltFac->setGeometry(QRect(460, 93, 101, 29));
        doubleSpinBoxF_MeltFac->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxF_MeltFac->setDecimals(6);
        doubleSpinBoxF_MeltFac->setMaximum(99);
        doubleSpinBoxF_MeltFac->setSingleStep(0.1);
        doubleSpinBoxF_MeltFac->setValue(1);
        textLabel1_35 = new QLabel(tab_5);
        textLabel1_35->setObjectName(QStringLiteral("textLabel1_35"));
        textLabel1_35->setGeometry(QRect(200, 92, 71, 31));
        tabWidget->addTab(tab_5, QString());

        retranslateUi(CalibDataFile);

        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(CalibDataFile);
    } // setupUi

    void retranslateUi(QDialog *CalibDataFile)
    {
        CalibDataFile->setWindowTitle(QApplication::translate("CalibDataFile", ": :   Calib Data File   : :", 0));
        groupBoxButtons->setTitle(QString());
        pushButtonHelp->setText(QApplication::translate("CalibDataFile", "Help", 0));
        pushButtonClose->setText(QApplication::translate("CalibDataFile", "Close", 0));
#ifndef QT_NO_TOOLTIP
        pushButtonRun->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pushButtonRun->setText(QApplication::translate("CalibDataFile", "Run", 0));
        groupBoxOutput->setTitle(QApplication::translate("CalibDataFile", "Output", 0));
        textLabelPara->setText(QApplication::translate("CalibDataFile", "Calib Data File", 0));
        pushButtonCalibDataFile->setText(QApplication::translate("CalibDataFile", "Browse", 0));
        textLabel1_20->setText(QApplication::translate("CalibDataFile", "Porosity", 0));
        textLabel1_21->setText(QApplication::translate("CalibDataFile", "MP KsatV", 0));
        textLabel1_22->setText(QApplication::translate("CalibDataFile", "Ksat V", 0));
        textLabel1_23->setText(QApplication::translate("CalibDataFile", "Alpha", 0));
        textLabel1_24->setText(QApplication::translate("CalibDataFile", "Beta", 0));
        textLabel1_25->setText(QApplication::translate("CalibDataFile", "InfilDepth", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_1), QApplication::translate("CalibDataFile", "    Soils    ", 0));
        textLabel1_6->setText(QApplication::translate("CalibDataFile", "Ksat V", 0));
        textLabel1_8->setText(QApplication::translate("CalibDataFile", "Ksat H", 0));
        textLabel1_9->setText(QApplication::translate("CalibDataFile", "MP Ksat H", 0));
        textLabel1_7->setText(QApplication::translate("CalibDataFile", "MP Depth", 0));
        textLabel1_10->setText(QApplication::translate("CalibDataFile", "MP fracV", 0));
        textLabel1_19->setText(QApplication::translate("CalibDataFile", "MP fracH", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("CalibDataFile", "  Geology  ", 0));
        textLabel1_29->setText(QApplication::translate("CalibDataFile", "Albedo", 0));
        textLabel1_30->setText(QApplication::translate("CalibDataFile", "RZ Depth", 0));
        textLabel1_31->setText(QApplication::translate("CalibDataFile", "Veg Frac", 0));
        textLabel1_32->setText(QApplication::translate("CalibDataFile", "Roughness", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("CalibDataFile", "  Land Cover  ", 0));
        textLabel1_13->setText(QApplication::translate("CalibDataFile", "Ksat H", 0));
        textLabel1_14->setText(QApplication::translate("CalibDataFile", "Rough", 0));
        textLabel1_15->setText(QApplication::translate("CalibDataFile", "Bed Th", 0));
        textLabel1_16->setText(QApplication::translate("CalibDataFile", "Ksat V", 0));
        textLabel1_17->setText(QApplication::translate("CalibDataFile", "Depth", 0));
        textLabel1_18->setText(QApplication::translate("CalibDataFile", "Width", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("CalibDataFile", "    River    ", 0));
        textLabel1_11->setText(QApplication::translate("CalibDataFile", "Temp", 0));
        textLabel1_12->setText(QApplication::translate("CalibDataFile", "Precip", 0));
        textLabel1_26->setText(QApplication::translate("CalibDataFile", "Transp", 0));
        textLabel1_27->setText(QApplication::translate("CalibDataFile", "Evap\n"
"Ground", 0));
        textLabel1_28->setText(QApplication::translate("CalibDataFile", "Evap\n"
"Canopy", 0));
        textLabel1_33->setText(QApplication::translate("CalibDataFile", "Melt Fac", 0));
        textLabel1_34->setText(QApplication::translate("CalibDataFile", "IS Max", 0));
        textLabel1_35->setText(QApplication::translate("CalibDataFile", "Thru Fall", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("CalibDataFile", "   Forcings   ", 0));
    } // retranslateUi

};

namespace Ui {
    class CalibDataFile: public Ui_CalibDataFile {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CALIBDATAFILE_H
