######################################################################
# Automatically generated by qmake (2.00a) Wed Apr 25 18:19:29 2007
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += about.h
FORMS += about.ui
SOURCES += main.cpp about.cpp
